# Generated by Django 5.1.2 on 2025-01-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('family', models.IntegerField()),
                ('ccavg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('education', models.IntegerField()),
                ('mortgage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personal_loan', models.BooleanField()),
                ('securities_account', models.BooleanField()),
                ('cd_account', models.BooleanField()),
                ('online', models.BooleanField()),
                ('creditcard', models.BooleanField()),
            ],
            options={
                'db_table': 'customer_data',
            },
        ),
    ]
